[build]
  # Build command (none needed for static frontend)
  command = ""
  
  # Directory to publish (current directory since index.html is here)
  publish = "."

[build.environment]
  # Set Node.js version if needed
  NODE_VERSION = "18"

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/Javascript/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/Styles/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA routing - redirect all non-file requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {path = "!/Javascript/*", path = "!/Styles/*", path = "!/img/*", path = "!/Activites/*", path = "!/JSON/*"}
